[tool.poetry]
name = "s3pypi"
version = "0.10.0"
description = "CLI for creating a Python Package Repository in an S3 bucket"
authors = [
    "Matteo De Wint <matteo@novemberfive.co>",
    "Ruben Van den Bossche <ruben@novemberfive.co>",
]
license = "MIT"
packages = [
    { include = "s3pypi" }
]

[tool.poetry.scripts]
s3pypi = "s3pypi.__main__:main"
s3pypi-admin = "s3pypi.admin.__main__:main"
s3pypi-infrastructure = "s3pypi.infrastructure.__main__:main"

[tool.poetry.dependencies]
basicauth = "^0.4.1"
boto3 = "^1.9.211"
Jinja2 = "^2.10.1"
passlib = "^1.7.1"
python = "~2.7 || ^3.5"
wheel = "^0.33.6"

[tool.poetry.dev-dependencies]
black = {version = "^19.3b0", allows-prereleases = true, python = "^3.6"}
flake8 = "^3.7.8"
isort = "^4.3.21"
moto = "^1.3.13"
pytest = ">=4.6.5"
pytest-cov = "^2.7.1"

[tool.black]
exclude = '''
      \.aws-sam
    | \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | build
    | cdk
    | dist
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
